In [15]:
import pandas as pd

# Път към файла (ако е в същата папка)
file_path = "customers-data.csv"

# Зареждане на CSV файла
df = pd.read_csv(file_path)

# Показване на редовете
df

# Информация за типовете данни
# print(df.info())

,customer_id,name,age,purchase_amount,product_category,purchase_date
0,1,Ivan Petrov,25.0,100.0,Electronics,2025-01-05
1,2,Maria Ivanova,30.0,200.0,Clothing,2025-01-06
2,2,Maria Ivanova,30.0,200.0,Clothing,2025-01-06
3,3,Georgi Georgiev,40.0,150.0,Books,2025-01-07
4,4,Anna Koleva,-5.0,50.0,Electronics,2025-01-08
5,5,NaN,28.0,NaN,Clothing,2025-01-09
6,6,Petar Dimitrov,35.0,300.0,Books,2025-01-10
7,7,Ivan Petrov,NaN,120.0,Electronics,2025-01-11
8,8,Maria Ivanova,32.0,250.0,Clothing,NaN
9,9,Georgi Georgiev,40.0,180.0,Electronics,2025-01-12

In [3]:
# Премахване на редове с липсващи стойности в name

df_clean = df.dropna(subset=["name"])
df_clean

,customer_id,name,age,purchase_amount,product_category,purchase_date
0,1,Ivan Petrov,25.0,100.0,Electronics,2025-01-05
1,2,Maria Ivanova,30.0,200.0,Clothing,2025-01-06
2,2,Maria Ivanova,30.0,200.0,Clothing,2025-01-06
3,3,Georgi Georgiev,40.0,150.0,Books,2025-01-07
4,4,Anna Koleva,-5.0,50.0,Electronics,2025-01-08
6,6,Petar Dimitrov,35.0,300.0,Books,2025-01-10
7,7,Ivan Petrov,NaN,120.0,Electronics,2025-01-11
8,8,Maria Ivanova,32.0,250.0,Clothing,NaN
9,9,Georgi Georgiev,40.0,180.0,Electronics,2025-01-12

In [16]:
# Попълване на липсващи стойности 
# Средна стойност за purchase_amount, медиана за age, Unknown за name
df_filled = df.copy()

df_filled["purchase_amount"] = df_filled["purchase_amount"].fillna(df_filled["purchase_amount"].mean())
df_filled["age"] = df_filled["age"].fillna(df_filled["age"].median())
df_filled["name"] = df_filled["name"].fillna("Unknown")

print(df_filled)

   customer_id             name   age  purchase_amount product_category  \
0            1      Ivan Petrov  25.0       100.000000      Electronics
1            2    Maria Ivanova  30.0       200.000000         Clothing
2            2    Maria Ivanova  30.0       200.000000         Clothing
3            3  Georgi Georgiev  40.0       150.000000            Books
4            4      Anna Koleva  -5.0        50.000000      Electronics
5            5          Unknown  28.0       172.222222         Clothing
6            6   Petar Dimitrov  35.0       300.000000            Books
7            7      Ivan Petrov  30.0       120.000000      Electronics
8            8    Maria Ivanova  32.0       250.000000         Clothing
9            9  Georgi Georgiev  40.0       180.000000      Electronics

  purchase_date
0    2025-01-05
1    2025-01-06
2    2025-01-06
3    2025-01-07
4    2025-01-08
5    2025-01-09
6    2025-01-10
7    2025-01-11
8           NaN
9    2025-01-12

In [21]:
# Добавяне на индикаторна колона за липсващи стойности в purchase_date
df_filled["missing_purchase_date_flag"] = df_filled["purchase_date"].isna().astype(int)
df_filled

,customer_id,name,age,purchase_amount,product_category,purchase_date,missing_purchase_date_flag
0,1,Ivan Petrov,25.0,100.000000,Electronics,2025-01-05,0
1,2,Maria Ivanova,30.0,200.000000,Clothing,2025-01-06,0
2,2,Maria Ivanova,30.0,200.000000,Clothing,2025-01-06,0
3,3,Georgi Georgiev,40.0,150.000000,Books,2025-01-07,0
4,4,Anna Koleva,-5.0,50.000000,Electronics,2025-01-08,0
5,5,Unknown,28.0,172.222222,Clothing,2025-01-09,0
6,6,Petar Dimitrov,35.0,300.000000,Books,2025-01-10,0
7,7,Ivan Petrov,30.0,120.000000,Electronics,2025-01-11,0
8,8,Maria Ivanova,32.0,250.000000,Clothing,NaN,1
9,9,Georgi Georgiev,40.0,180.000000,Electronics,2025-01-12,0

In [6]:
# Откриване на дубликати
df_filled[df_filled.duplicated()]

# Премахване на дубликати
df_no_duplicates = df_filled.drop_duplicates()
df_no_duplicates

,customer_id,name,age,purchase_amount,product_category,purchase_date,missing_purchase_date_flag
0,1,Ivan Petrov,25.0,100.000000,Electronics,2025-01-05,0
1,2,Maria Ivanova,30.0,200.000000,Clothing,2025-01-06,0
3,3,Georgi Georgiev,40.0,150.000000,Books,2025-01-07,0
4,4,Anna Koleva,-5.0,50.000000,Electronics,2025-01-08,0
5,5,Unknown,28.0,172.222222,Clothing,2025-01-09,0
6,6,Petar Dimitrov,35.0,300.000000,Books,2025-01-10,0
7,7,Ivan Petrov,30.0,120.000000,Electronics,2025-01-11,0
8,8,Maria Ivanova,32.0,250.000000,Clothing,NaN,1
9,9,Georgi Georgiev,40.0,180.000000,Electronics,2025-01-12,0

In [9]:
# Откриване на отрицателни възрасти или над 120
invalid_age = df[(df["age"] < 0) | (df["age"] > 120)]
invalid_age

# Замяна на отрицателните възрасти и възрасти над 120 с NaN
df_corrected = df.copy()
df_corrected["age"] = df["age"].apply(lambda x: None if (x < 0 or x > 120) else x)
df_corrected

,customer_id,name,age,purchase_amount,product_category,purchase_date,age_binned
0,1,Ivan Petrov,25.0,100.0,Electronics,2025-01-05,2.0
1,2,Maria Ivanova,30.0,200.0,Clothing,2025-01-06,2.0
2,2,Maria Ivanova,30.0,200.0,Clothing,2025-01-06,2.0
3,3,Georgi Georgiev,40.0,150.0,Books,2025-01-07,2.0
4,4,Anna Koleva,NaN,50.0,Electronics,2025-01-08,0.0
5,5,NaN,28.0,NaN,Clothing,2025-01-09,2.0
6,6,Petar Dimitrov,35.0,300.0,Books,2025-01-10,2.0
7,7,Ivan Petrov,NaN,120.0,Electronics,2025-01-11,2.0
8,8,Maria Ivanova,32.0,250.0,Clothing,NaN,2.0
9,9,Georgi Georgiev,40.0,180.0,Electronics,2025-01-12,2.0

In [4]:
# Преобразуване на колоната в тип datetime
df['purchase_date'] = pd.to_datetime(df['purchase_date'])

# Създаване на нови колони: ден от седмицата и месец
df['day_of_week'] = df['purchase_date'].dt.day_name()
df['month'] = df['purchase_date'].dt.month_name()

print(df)

   customer_id             name   age  purchase_amount product_category  \
0            1      Ivan Petrov  25.0            100.0      Electronics
1            2    Maria Ivanova  30.0            200.0         Clothing
2            2    Maria Ivanova  30.0            200.0         Clothing
3            3  Georgi Georgiev  40.0            150.0            Books
4            4      Anna Koleva  -5.0             50.0      Electronics
5            5              NaN  28.0              NaN         Clothing
6            6   Petar Dimitrov  35.0            300.0            Books
7            7      Ivan Petrov   NaN            120.0      Electronics
8            8    Maria Ivanova  32.0            250.0         Clothing
9            9  Georgi Georgiev  40.0            180.0      Electronics

  purchase_date day_of_week    month
0    2025-01-05      Sunday  January
1    2025-01-06      Monday  January
2    2025-01-06      Monday  January
3    2025-01-07     Tuesday  January
4    2025-01-08   Wednesday  January
5    2025-01-09    Thursday  January
6    2025-01-10      Friday  January
7    2025-01-11    Saturday  January
8           NaT         NaN      NaN
9    2025-01-12      Sunday  January

In [6]:
from sklearn.preprocessing import LabelEncoder

# Кодиране с етикети (label encoding) – всяка категория се заменя с цяло число
encoder = LabelEncoder()
df["category_encoded"] = encoder.fit_transform(df["product_category"])
print(df)

   customer_id             name   age  purchase_amount product_category  \
0            1      Ivan Petrov  25.0            100.0      Electronics
1            2    Maria Ivanova  30.0            200.0         Clothing
2            2    Maria Ivanova  30.0            200.0         Clothing
3            3  Georgi Georgiev  40.0            150.0            Books
4            4      Anna Koleva  -5.0             50.0      Electronics
5            5              NaN  28.0              NaN         Clothing
6            6   Petar Dimitrov  35.0            300.0            Books
7            7      Ivan Petrov   NaN            120.0      Electronics
8            8    Maria Ivanova  32.0            250.0         Clothing
9            9  Georgi Georgiev  40.0            180.0      Electronics

  purchase_date day_of_week    month  category_encoded
0    2025-01-05      Sunday  January                 2
1    2025-01-06      Monday  January                 1
2    2025-01-06      Monday  January                 1
3    2025-01-07     Tuesday  January                 0
4    2025-01-08   Wednesday  January                 2
5    2025-01-09    Thursday  January                 1
6    2025-01-10      Friday  January                 0
7    2025-01-11    Saturday  January                 2
8           NaT         NaN      NaN                 1
9    2025-01-12      Sunday  January                 2

In [7]:
# кодиране с бинарни стойности (one-hot encoding) за product_category
df_ohe = pd.get_dummies(df, columns=["product_category"], prefix="cat")
print(df_ohe)

   customer_id             name   age  purchase_amount purchase_date  \
0            1      Ivan Petrov  25.0            100.0    2025-01-05
1            2    Maria Ivanova  30.0            200.0    2025-01-06
2            2    Maria Ivanova  30.0            200.0    2025-01-06
3            3  Georgi Georgiev  40.0            150.0    2025-01-07
4            4      Anna Koleva  -5.0             50.0    2025-01-08
5            5              NaN  28.0              NaN    2025-01-09
6            6   Petar Dimitrov  35.0            300.0    2025-01-10
7            7      Ivan Petrov   NaN            120.0    2025-01-11
8            8    Maria Ivanova  32.0            250.0           NaT
9            9  Georgi Georgiev  40.0            180.0    2025-01-12

  day_of_week    month  category_encoded  cat_Books  cat_Clothing  \
0      Sunday  January                 2          0             0
1      Monday  January                 1          0             1
2      Monday  January                 1          0             1
3     Tuesday  January                 0          1             0
4   Wednesday  January                 2          0             0
5    Thursday  January                 1          0             1
6      Friday  January                 0          1             0
7    Saturday  January                 2          0             0
8         NaN      NaN                 1          0             1
9      Sunday  January                 2          0             0

   cat_Electronics
0                1
1                0
2                0
3                0
4                1
5                0
6                0
7                1
8                0
9                1

In [3]:
# Min–Max скалиране
from sklearn.preprocessing import MinMaxScaler

# Избираме числовите колони за скалиране
numeric_cols = ["age", "purchase_amount"]

# Създаваме MinMaxScaler
scaler = MinMaxScaler()

# Прилагаме скалирането (пропуска None/NaN стойности)
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

print(df)

   customer_id             name       age  purchase_amount product_category  \
0            1      Ivan Petrov  0.666667             0.20      Electronics
1            2    Maria Ivanova  0.777778             0.60         Clothing
2            2    Maria Ivanova  0.777778             0.60         Clothing
3            3  Georgi Georgiev  1.000000             0.40            Books
4            4      Anna Koleva  0.000000             0.00      Electronics
5            5              NaN  0.733333              NaN         Clothing
6            6   Petar Dimitrov  0.888889             1.00            Books
7            7      Ivan Petrov       NaN             0.28      Electronics
8            8    Maria Ivanova  0.822222             0.80         Clothing
9            9  Georgi Georgiev  1.000000             0.52      Electronics

  purchase_date
0    2025-01-05
1    2025-01-06
2    2025-01-06
3    2025-01-07
4    2025-01-08
5    2025-01-09
6    2025-01-10
7    2025-01-11
8           NaN
9    2025-01-12

In [12]:
import numpy as np

# Логаритмична трансформация
df['purchase_log'] = np.log1p(df['purchase_amount'])  # log(x+1)

print(df)

   customer_id             name   age  purchase_amount product_category  \
0            1      Ivan Petrov  25.0            100.0      Electronics
1            2    Maria Ivanova  30.0            200.0         Clothing
2            2    Maria Ivanova  30.0            200.0         Clothing
3            3  Georgi Georgiev  40.0            150.0            Books
4            4      Anna Koleva  -5.0             50.0      Electronics
5            5              NaN  28.0              NaN         Clothing
6            6   Petar Dimitrov  35.0            300.0            Books
7            7      Ivan Petrov   NaN            120.0      Electronics
8            8    Maria Ivanova  32.0            250.0         Clothing
9            9  Georgi Georgiev  40.0            180.0      Electronics

  purchase_date  purchase_log
0    2025-01-05      4.615121
1    2025-01-06      5.303305
2    2025-01-06      5.303305
3    2025-01-07      5.017280
4    2025-01-08      3.931826
5    2025-01-09           NaN
6    2025-01-10      5.707110
7    2025-01-11      4.795791
8           NaN      5.525453
9    2025-01-12      5.198497

In [19]:
from sklearn.preprocessing import KBinsDiscretizer

# Групиране на purchase_amount в 3 интервала
discretizer = KBinsDiscretizer(
    n_bins=3,                # брой интервали
    encode="ordinal",        # представяне с цели числа
    strategy="uniform"       # равни интервали
)
# Преобразуване на колоната purchase_amount
df["purchase_amount_binned"] = discretizer.fit_transform(df_filled[["purchase_amount"]])
print(df)

   customer_id             name   age  purchase_amount product_category  \
0            1      Ivan Petrov  25.0            100.0      Electronics
1            2    Maria Ivanova  30.0            200.0         Clothing
2            2    Maria Ivanova  30.0            200.0         Clothing
3            3  Georgi Georgiev  40.0            150.0            Books
4            4      Anna Koleva  -5.0             50.0      Electronics
5            5              NaN  28.0              NaN         Clothing
6            6   Petar Dimitrov  35.0            300.0            Books
7            7      Ivan Petrov   NaN            120.0      Electronics
8            8    Maria Ivanova  32.0            250.0         Clothing
9            9  Georgi Georgiev  40.0            180.0      Electronics

  purchase_date  purchase_amount_binned
0    2025-01-05                     0.0
1    2025-01-06                     1.0
2    2025-01-06                     1.0
3    2025-01-07                     1.0
4    2025-01-08                     0.0
5    2025-01-09                     1.0
6    2025-01-10                     2.0
7    2025-01-11                     0.0
8           NaN                     2.0
9    2025-01-12                     1.0

In [15]:
# IQR метод
Q1_age = df['age'].quantile(0.25)
Q3_age = df['age'].quantile(0.75)
IQR_age = Q3_age - Q1_age

Q1_purchase = df['purchase_amount'].quantile(0.25)
Q3_purchase = df['purchase_amount'].quantile(0.75)
IQR_purchase = Q3_purchase - Q1_purchase

# Маркиране на outliers
df['age_outlier'] = ((df['age'] < Q1_age - 1.5*IQR_age) | (df['age'] > Q3_age + 1.5*IQR_age)).astype(int)
df['purchase_outlier'] = ((df['purchase_amount'] < Q1_purchase - 1.5*IQR_purchase) | 
                          (df['purchase_amount'] > Q3_purchase + 1.5*IQR_purchase)).astype(int)

df

,customer_id,name,age,purchase_amount,product_category,purchase_date,purchase_log,age_outlier,purchase_outlier
0,1,Ivan Petrov,25.0,100.0,Electronics,2025-01-05,4.615121,0,0
1,2,Maria Ivanova,30.0,200.0,Clothing,2025-01-06,5.303305,0,0
2,2,Maria Ivanova,30.0,200.0,Clothing,2025-01-06,5.303305,0,0
3,3,Georgi Georgiev,40.0,150.0,Books,2025-01-07,5.017280,0,0
4,4,Anna Koleva,-5.0,50.0,Electronics,2025-01-08,3.931826,1,0
5,5,NaN,28.0,NaN,Clothing,2025-01-09,NaN,0,0
6,6,Petar Dimitrov,35.0,300.0,Books,2025-01-10,5.707110,0,0
7,7,Ivan Petrov,NaN,120.0,Electronics,2025-01-11,4.795791,0,0
8,8,Maria Ivanova,32.0,250.0,Clothing,NaN,5.525453,0,0
9,9,Georgi Georgiev,40.0,180.0,Electronics,2025-01-12,5.198497,0,0